### ISSUE TITLE
Not compatible with electron-pos-printer package

### ISSUE THREAD

**Issue by brothergiez** [StarLederer/vite-electron-builder-svelte#3]
when im combine with [`electron-pos-printer`](https://www.npmjs.com/package/electron-pos-printer) for printing receipt, its not printing... always time out because tha package will creating another browserwindow for showing the print preview.

**Comment by StarLederer** [comment]
Thanks for opening this issue!

Somehow I didn't see a notification for this. Perhaps you opened this just as I ended support for this for this fork. I no longer use or recommend Electron.

That is a very specific use-case you got there. I don't even know what a thermal printer is. I hope you already solved the issue, otherwise I recommend trying your luck again with Tauri
